
name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/grade-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/grade-api:${{ github.sha }}

      - name: Update GitOps repository
        shell: bash
        env:
          GIT_TOKEN: ${{ secrets.GITOPS_PAT }}
        run: |
          # Configure git credential store
          git config --global credential.helper store
          echo "https://${GIT_TOKEN}:x-oauth-basic@github.com" > ~/.git-credentials
          
          # Remove any existing gitops directory
          rm -rf gitops
          
          # Clone repository using HTTPS URL without token
          git clone https://github.com/rslim087a/grade-api-gitops.git gitops
          cd gitops
          
          if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i '' "s|image: .*|image: ${DOCKERHUB_USERNAME}/grade-api:${{ github.sha }}|g" deployment.yaml
          else
            sed -i "s|image: .*|image: ${DOCKERHUB_USERNAME}/grade-api:${{ github.sha }}|g" deployment.yaml
          fi
          
          # Commit changes
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add deployment.yaml
          git commit -m "Update image to ${{ secrets.DOCKERHUB_USERNAME }}/grade-api:${{ github.sha }}"
          
          # Push
          git push -f https://${GIT_TOKEN}@github.com/rslim087a/grade-api-gitops.git main


