name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/datahub-app:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/datahub-app:${{ github.sha }}

      - name: Update GitOps repository
        shell: bash
        env:
          GIT_TOKEN: ${{ secrets.GITOPS_PAT }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          # Clone GitOps repo
          rm -rf argocd-dataapp
          git clone https://github.com/RameezAhmedZaka/argocd-dataapp.git argocd-dataapp
          cd argocd-dataapp/argocd-dataapp
          ls -l

          sed -i "s|image: .*|image: ${DOCKERHUB_USERNAME}/dataapp:${GITHUB_SHA}|g" deployment.yaml

          # Commit and push
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add deployment.yaml
          git commit -m "Update image to ${DOCKERHUB_USERNAME}/dataapp:${{ github.sha }}"
          git push https://$GIT_TOKEN@github.com/RameezAhmedZaka/argocd-dataapp.git HEAD:main

